version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/home/node/app
    env_file:
      - .env.development
    command: 'npm run start:dev'