version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: 'npm run start'